export const heartReflectionQuestions = [
  { id: "whatDrivesYou", label: "What drives you? What are you passionate about?" },
  { id: "whoToHelp", label: "Who do you feel called to help?" },
  { id: "needsDrawnTo", label: "What needs are you drawn to?" },
  { id: "passionateCause", label: "What cause are you most passionate about?" },
];

export const peopleToServeOptions = [
  "Children", "College Students", "Disabled", "Divorced", "Elderly",
  "Empty Nesters", "Homeless", "Hospitalized", "Infants", "Men",
  "Parents", "Poor", "Prisoners", "Single Parents", "Singles",
  "Teen Moms", "Unemployed", "Widowed", "Women", "Young Married", "Youth",
];

export const issuesAndCausesOptions = [
  "Abuse/Violence", "Alcoholism", "At-risk Children", "Compulsive Behavior",
  "Deafness", "Disabilities", "Divorce", "Drug Abuse", "Education",
  "Environment", "Ethics", "Finances", "Health/Fitness", "Terminal Sickness",
  "Homelessness", "Injustice Issues", "Law/Justice System", "Marriage/Family",
  "Parenting", "Policy/Politics", "Poverty/Hunger", "Sanctity of Life",
  "Sexuality", "Spiritual Apathy",
];

export const spiritualGiftQuestions: { id: number; text: string }[] = [
  { id: 1, text: "I like to organize people, tasks, and events." },
  { id: 2, text: "I would like to start churches in places where they do not presently exist." },
  { id: 3, text: "I enjoy working creatively with wood, cloth, paints, metal, glass, or other materials." },
  { id: 4, text: "I enjoy challenging people's perspective of God by using various forms of art." },
  { id: 5, text: "I can readily distinguish between spiritual truth and error, good and evil." },
  { id: 6, text: "I tend to see the potential in people." },
  { id: 7, text: "I communicate the gospel to others with clarity and effectiveness." },
  { id: 8, text: "I find it natural and easy to trust God to answer my prayers." },
  { id: 9, text: "I give liberally and joyfully to people in financial need or to projects requiring support." },
  { id: 10, text: "I enjoy working behind the scenes to support the work of others." },
  { id: 11, text: "I view my home as a place to minister to people in need." },
  { id: 12, text: "I take prayer requests from others and consistently pray for them." },
  { id: 13, text: "I am asked by people who want to know my perspective on a particular passage or biblical truth." },
  { id: 14, text: "I am able to motivate others to accomplish a goal." },
  { id: 15, text: "I empathize with hurting people and desire to help in their healing process." },
  { id: 16, text: "I can speak in a way that results in conviction and change in the lives of others." },
  { id: 17, text: "I enjoy spending time nurturing and caring for others." },
  { id: 18, text: "I am able to communicate God's work effectively." },
  { id: 19, text: "I am often sought out by others for advice about spiritual or personal matters." },
  { id: 20, text: "I am careful, thorough, and skilled at managing details." },
  { id: 21, text: "I am attracted to the idea of serving in another country or ethnic community." },
  { id: 22, text: "I am skilled in working with different kinds of tools." },
  { id: 23, text: "I enjoy developing and using my artistic skills. (art, drama, music, photography, etc.)" },
  { id: 24, text: "I frequently am able to judge a person's character based upon first impressions." },
  { id: 25, text: "I enjoy reassuring and strengthening those who are discouraged." },
  { id: 26, text: "I consistently look for opportunities to build relationships with non-Christians." },
  { id: 27, text: "I have confidence in God's continuing provision and help, even in difficult times." },
  { id: 28, text: "I give more than a tithe so that kingdom work can be accomplished." },
  { id: 29, text: "I enjoy doing routine tasks that support the ministry." },
  { id: 30, text: "I enjoy meeting new people and helping them to feel welcomed." },
  { id: 31, text: "I enjoy praying for long periods of time and always feel impressed on what to pray for." },
  { id: 32, text: "I receive information from the Spirit that I did not acquire through natural means." },
  { id: 33, text: "I am able to influence others to achieve a vision." },
  { id: 34, text: "I can patiently support those going through painful experiences as they try to stabilize their lives." },
  { id: 35, text: "I feel responsible to confront others with the truth." },
  { id: 36, text: "I have compassion for wandering believers and want to protect them." },
  { id: 37, text: "I can spend time in study knowing that presenting truth will make a difference in people's lives." },
  { id: 38, text: "I can often find simple, practical solutions in the midst of conflict or confusion." },
  { id: 39, text: "I can clarify goals and develop strategies or plans to accomplish them." },
  { id: 40, text: "I am willing to take an active part in starting a new church." },
  { id: 41, text: "I enjoy making things for use in ministry." },
  { id: 42, text: "I help people understand themselves, others and God better through artistic expression." },
  { id: 43, text: "I can see through phoniness or deceit before it is evident to others." },
  { id: 44, text: "I give hope to others by directing them to the promises of God." },
  { id: 45, text: "I am effective at adapting the gospel message so that it connects with an individual's felt needs." },
  { id: 46, text: "I believe that God will help me to accomplish great things." },
  { id: 47, text: "I manage my money well in order to free more of it for giving." },
  { id: 48, text: "I willingly take on a variety of odd jobs around the church to meet the needs of others." },
  { id: 49, text: "I genuinely believe the Lord directs strangers to me who need to get connected to others." },
  { id: 50, text: "I am conscious of ministering to others as I pray." },
  { id: 51, text: "I am committed to reading and studying Scripture, to understand Biblical truth fully." },
  { id: 52, text: "I can adjust my leadership style to bring out the best in others." },
  { id: 53, text: "I enjoy helping people sometimes regarded as undeserving or beyond help." },
  { id: 54, text: "I boldly expose cultural trends, teachings, or events, which contradict Biblical principles." },
  { id: 55, text: "I like to provide guidance for the whole person – relationally, emotionally, spiritually, etc..." },
  { id: 56, text: "I devote considerable time to learning new Biblical truths in order to communicate them to others." },
  { id: 57, text: "I can easily select the most effective course of action from among several alternatives." },
  { id: 58, text: "I can identify and effectively use the resources needed to accomplish tasks." },
  { id: 59, text: "I can adapt well to different cultures and surroundings." },
  { id: 60, text: "I can visualize how something should be constructed before I build it." },
  { id: 61, text: "I like finding new and fresh ways of communicating God's truth." },
  { id: 62, text: "I tend to see rightness or wrongness in situations." },
  { id: 63, text: "I reassure those who need to take courageous action in their faith, family, or life." },
  { id: 64, text: "I invite unbelievers to accept Christ as their Savior." },
  { id: 65, text: "I trust God in circumstances where success cannot be guaranteed by human effort alone." },
  { id: 66, text: "I am challenged to limit my lifestyle in order to give away higher percentages of my income." },
  { id: 67, text: "I see spiritual significance in doing practical tasks." },
  { id: 68, text: "I like to create a place where people do not feel that they are alone." },
  { id: 69, text: "I pray with confidence because I know that God works in response to prayer." },
  { id: 70, text: "I have insight or just know something to be true." },
  { id: 71, text: "I set goals and manage people and resources effectively to accomplish them." },
  { id: 72, text: "I have great compassion for hurting people." },
  { id: 73, text: "I see most actions as right or wrong, and feel the need to correct the wrong." },
  { id: 74, text: "I can faithfully provide long-term support and concern for others." },
  { id: 75, text: "I like to take a systematic approach to my study of the Bible." },
  { id: 76, text: "I can anticipate the likely consequences of an individual's or a group's action." },
  { id: 77, text: "I like to help organizations or groups become more efficient." },
  { id: 78, text: "I can relate to others in culturally sensitive ways." },
  { id: 79, text: "I honor God with my handcrafted gifts." },
  { id: 80, text: "I apply various artistic expressions to communicate God's truth." },
  { id: 81, text: "I receive affirmation from others concerning the reliability of my insights or perceptions." },
  { id: 82, text: "I strengthen those who are wavering in their faith." },
  { id: 83, text: "I openly tell people that I am a Christian and want them to ask me about my faith." },
  { id: 84, text: "I am convinced of God's daily Presence and action in my life." },
  { id: 85, text: "I like knowing that my financial support makes a real difference in the lives of God's people." },
  { id: 86, text: "I like to find small things that need to be done and often do them without being asked." },
  { id: 87, text: "I enjoy entertaining people and opening my home to others." },
  { id: 88, text: "When I hear about needy situations, I feel burdened to pray." },
  { id: 89, text: "I have suddenly known some things about others, but did not know how I knew them." },
  { id: 90, text: "I influence others to perform to the best of their capability." },
  { id: 91, text: "I can look beyond a person's handicaps or problems to see a life that matters to God." },
  { id: 92, text: "I like people who are honest and will speak the truth." },
  { id: 93, text: "I enjoy giving guidance and practical support to a small group of people." },
  { id: 94, text: "I can communicate Scripture in ways that motivate others to study and want to learn more." },
  { id: 95, text: "I give practical advice to help others through complicated situations." },
];

export interface TraitGroup {
  id: number;
  traits: string[];
}

export const experienceQuestions = [
  { id: "studiedInSchool", label: "What did you study in school?" },
  { id: "occupation", label: "What do you do for a living? If retired, what did you do?" },
  { id: "hobbies", label: "What hobbies do you enjoy?" },
  { id: "churchServing", label: "Within the church, where have you enjoyed serving in the past?" },
  { id: "painfulExperience", label: "Many times, your passion will come out of your pain in life. If you are able & willing, please share the most painful experience that you have been through in your life." },
];

export const abilitiesOptions = [
  "Adapting", "Administrating", "Analyzing", "Building", "Coaching",
  "Communicating", "Competing", "Computing", "Connecting", "Consulting",
  "Cooking", "Coordination", "Counseling", "Decorating", "Designing",
  "Developing", "Directing", "Editing", "Encouraging", "Engineering",
  "Excelling", "Facilitating", "Forecasting", "Implementing", "Improving",
  "Influencing", "Landscaping", "Leading", "Learning", "Managing",
  "Mentoring", "Motivating", "Negotiating", "Operating", "Organizing",
  "Performing", "Persevering", "Pioneering", "Planning", "Promoting",
  "Recruiting", "Repairing", "Researching", "Resourcing", "Serving",
  "Shopping", "Strategizing", "Teaching", "Traveling", "Visualizing",
  "Welcoming", "Writing",
];

export const personalityTraitGroups: TraitGroup[] = [
  { id: 1, traits: ["Kind, softhearted, sweet", "Influencing, convincing", "Unassuming, composed, self-controlled", "Independent, resourceful, one-of-a-kind"] },
  { id: 2, traits: ["Likeable, fascinating, fun", "Reasonable, fair", "Willful, firm, decision-maker", "Supportive, pleasant, warm"] },
  { id: 3, traits: ["Observant, careful", "Brave, unafraid, likes a challenge", "Faithful, steadfast", "Appealing, refreshing, lively"] },
  { id: 4, traits: ["Objective, balanced, open-minded", "Willing to help, thoughtful", "Determined, unbending, stubborn", "Lighthearted, upbeat"] },
  { id: 5, traits: ["Humorous, funny", "Specific, exact, correct", "Gutsy, daring, bold", "Relaxed, content, not excitable"] },
  { id: 6, traits: ["Aggressive, driven, wants to win", "Accommodating, considers others, caring", "Excitable, fun-seeking", "Conforming, cooperative"] },
  { id: 7, traits: ["Particular, choosy", "Devoted, loyal, attends to duties", "Tough-minded, unyielding, purposeful", "Animated, fun-loving, joking"] },
  { id: 8, traits: ["Confident, courageous, fearless", "Inspiring, influential, enthusiastic", "Does not resist, submits easily", "Avoids attention, modest"] },
  { id: 9, traits: ["Outgoing, makes friends easily", "Patient, lenient, shows mercy, stable", "Self-sufficient, goal achieving", "Private, subdued, appropriate"] },
  { id: 10, traits: ["Risk-taking, thrill-seeking, daring", "Teachable, willing to be convinced", "Sociable, big-hearted, personable", "Agreeable, easygoing, not extreme"] },
  { id: 11, traits: ["Expressive, likes to talk", "Moderate, easily swayed", "Follows routine, decides carefully", "Self-confident, makes decisions quickly and easily"] },
  { id: 12, traits: ["Persuasive, smooth, at ease with people", "Adventurous, unflinching", "Courteous, respectful, tactful", "Contented, easily pleased"] },
  { id: 13, traits: ["Enjoys competition, persistent, entrepreneur", "Life of the party, entertaining, draws attention", "Vulnerable, gullible, easily influenced", "Anxious, apprehensive, hesitant"] },
  { id: 14, traits: ["Watchful, cautious, weighs risks", "Ambitious, takes charge", "Wholeheartedly convinced, talks others into", "Comfortable, good-natured, welcoming"] },
  { id: 15, traits: ["Ready to help, goes along with, trusting", "Easily excited, high strung", "Compliant, follows rules, not argumentative", "Vibrant, enterprising, energetic"] },
  { id: 16, traits: ["Self-assured, positive, optimistic", "Kindhearted, sentimental, responsive", "Evaluating, examining, questioning", "Assertive, forceful, alert"] },
  { id: 17, traits: ["Self-disciplined, controlled, methodical", "Unselfish, concerned for others", "Demonstrates feelings and emotions outwardly", "Committed, not easily defeated nor discouraged"] },
  { id: 18, traits: ["Commendable, desires recognition", "Pleasing, sharing, gracious", "Selective, chooses carefully", "Emphatic, insistent, demanding"] },
  { id: 19, traits: ["Formal, shows proper respect, restrained", "Innovative, pioneering, tries new things", "Happy, expects good things to happen", "Harmonious, obliging, helpful"] },
  { id: 20, traits: ["Confronting, challenging", "Adjustable, able to change", "Unruffled, indifferent, casual", "Cheerful, unworried, playful"] },
  { id: 21, traits: ["Believes in others, open, trustful", "At peace, pleased, satisfied", "Unquestionable confidence, certain", "Even-tempered, level-headed, unhurried"] },
  { id: 22, traits: ["Compatible, enjoys people, popular", "Informed, refined, perceptive", "Dynamic, powerful, spirited", "Tolerant, compassionate, merciful"] },
  { id: 23, traits: ["Fun to be with, sociable", "Precise, factual, accurate", "Direct, speaks frankly", "Quiet, soft-spoken, reserved"] },
  { id: 24, traits: ["Restless, fidgety, easily bored", "Peaceable, helps others, friendly", "Well-liked, impulsive, charming", "Systematic, tidy, attentive to details"] },
];
